#!/usr/bin/python

"""
Generates sine wave tables for ffso.c as includable C code. The resulting
table consists of unsigned 8-bit samples stored in the AVR's progmem.
"""

from math import pi, sin

def generate_sintab(f_pwm, f_signal, name):
    sample_count = int(f_pwm / f_signal)
    print "#define %s_LEN %d" % (name.upper(), sample_count)
    print "static const uint8_t %s[%d] PROGMEM = {" % (name, sample_count)
    delta_phi = (2 * pi) / sample_count
    phi = 0
    samples = []

    for i in range(sample_count):
        sample = int((sin(phi) + 1) * 128)
        samples.append(sample)
        phi += delta_phi

    print ", ".join(str(sample) for sample in samples)
    print "};"

print "/* This file is generated by util/generate-sintabs.py - do not edit by hand */"
generate_sintab(62500, 50, "sintab_50")
generate_sintab(62500, 67.5, "sintab_67_5")
